[package]
name = "ringcrypt-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ringcrypt-ntt.workspace = true
ringcrypt-ss.workspace = true
ringcrypt-scheme.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
console_error_panic_hook.workspace = true

[features]
default = []
