[package]
name = "ringcrypt-ss"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
rand.workspace = true
rand_pcg.workspace = true
serde.workspace = true
getrandom.workspace = true

[features]
default = []
